version: "3.9"
name: "api-compose"
services:
  task-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    links:
      - postgres

  postgres:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin


  


